Default: &defaults
  database: tomato-monad.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: tomato-monad_test.sqlite3
  <<: *defaults

Staging:
  database: tomato-monad_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: tomato-monad_production.sqlite3
  poolsize: 100
  <<: *defaults
